name: ops Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '42 7 25 * *'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        preset: ['k8s', 'microk8s']
        test: ['test_direct_connection', 'test_with_tls', 'test_relation_units']

    steps:
      - run: |
           # Work around https://github.com/jnsgruk/concierge/issues/30
           sudo apt-get remove -y docker-ce docker-ce-cli containerd.io
           sudo rm -rf /run/containerd
      - name: Make sure snap/apt cache folders exist before restoring cache
        run: |
          sudo mkdir -p /var/lib/snapd/cache
          sudo mkdir -p /var/cache/apt
          sudo chown -R $USER:$USER /var/snap
          sudo chown -R $USER:$USER /var/lib/snapd/cache
          sudo chown -R $USER:$USER /var/cache/apt
          sudo chmod -R a+r /var/snap
          sudo chmod -R a+r /var/lib/snapd/cache
          sudo chmod -R a+r /var/cache/apt
      - uses: actions/cache@v4
        id: snap-cache
        with:
          path: |
            /var/snap/yq
            /var/snap/rockcraft
            /var/snap/charmcraft
            /var/snap/jq
            /var/snap/kubectl
            /var/snap/juju
            /var/lib/snapd/cache
          key: ${{ runner.os }}-snapd-${{ matrix.preset }}
      - uses: actions/cache@v4
        id: apt-cache
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ matrix.preset }}
      - name: Adjust snap permissions to ensure concierge can run
        run: |
          sudo chown -R $USER:$USER /var/snap
          sudo chmod -R a+r /var/snap
      - run: sudo snap install --classic concierge
      - run: >
          sudo concierge prepare
          --juju-channel=3/stable
          --charmcraft-channel=3.x/stable
          -p "${{ matrix.preset }}"
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc  # v6.4.3
      - run: uv tool install tox --with tox-uv
      - run: tox -e integration -- --log-cli-level=INFO -s -k "${{ matrix.test }}"
      - name: Adjust snap and apt cache permissions to ensure cache can be saved
        run: |
          sudo chown -R $USER:$USER /var/snap
          sudo chown -R $USER:$USER /var/lib/snapd/cache
          sudo chown -R $USER:$USER /var/cache/apt
          sudo chmod -R a+r /var/snap
          sudo chmod -R a+r /var/lib/snapd/cache
          sudo chmod -R a+r /var/cache/apt
          